=== hmrc/interest-restriction-return-dynamic-stub/conf/resources/cir/schemas/revoke.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Revoke IRR Reporting Company Request Schema",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "accountingPeriod",
    "agentDetails",
    "authorisingCompanies",
    "declaration",
    "isReportingCompanyRevokingItself",
    "reportingCompany"
  ],
  "properties": {
    "agentDetails": {
      "type": "object",
      "additionalProperties": false,
      "required": ["agentActingOnBehalfOfCompany"],
      "properties": {
        "agentActingOnBehalfOfCompany": {
          "type": "boolean"
        },
        "agentName": {
          "$ref": "#/definitions/ukCompanyNameType"
        }
      }
    },
    "reportingCompany": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "companyName",
        "ctutr",
        "sameAsUltimateParent"
      ],
      "properties": {
        "companyName": {
          "$ref": "#/definitions/ukCompanyNameType"
        },
        "ctutr": {
          "$ref": "#/definitions/utrType"
        },
        "sameAsUltimateParent": {
          "type": "boolean"
        }
      }
    },
    "isReportingCompanyRevokingItself": {
      "type": "boolean"
    },
    "companyMakingRevocation": {
      "type": "object",
      "additionalProperties": false,
      "required": ["companyName"],
      "properties": {
        "companyName": {
          "$ref": "#/definitions/globalCompanyNameType"
        },
        "countryOfIncorporation": {
          "$ref": "#/definitions/countryCodesType"
        },
        "ctutr": {
          "$ref": "#/definitions/utrType"
        },
        "legalEntityIdentifier": {
          "$ref": "#/definitions/legalEntityIdentifierType"
        }
      }
    },
    "ultimateParentCompany": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "companyName",
        "isUk"
      ],
      "properties": {
        "isUk": {
          "type": "boolean"
        },
        "companyName": {
          "$ref": "#/definitions/globalCompanyNameType"
        },
        "ctutr": {
          "$ref": "#/definitions/utrType"
        },
        "sautr": {
          "$ref": "#/definitions/utrType"
        },
        "knownAs": {
          "$ref": "#/definitions/globalCompanyNameType"
        },
        "countryOfIncorporation": {
          "$ref": "#/definitions/countryCodesType"
        },
        "legalEntityIdentifier": {
          "$ref": "#/definitions/legalEntityIdentifierType"
        }
      }
    },
    "accountingPeriod": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "endDate",
        "startDate"
      ],
      "properties": {
        "startDate": {
          "$ref": "#/definitions/dateType"
        },
        "endDate": {
          "$ref": "#/definitions/dateType"
        }
      }
    },
    "authorisingCompanies": {
      "type": "array",
      "minItems": 1,
      "maxItems": 2147483647,
      "uniqueItems": true,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "companyName",
          "utr"
        ],
        "properties": {
          "companyName": {
            "$ref": "#/definitions/ukCompanyNameType"
          },
          "utr": {
            "$ref": "#/definitions/utrType"
          },
          "consenting": {
            "type": "boolean"
          }
        }
      }
    },
    "declaration": {
      "type": "boolean"
    }
  },
  "definitions": {
    "ukCompanyNameType": {
      "type": "string",
      "pattern": "^[ -~¡-ÿĀ-ʯḀ-ỿ‐-―‘-‟₠-₿ÅK]{1,160}$"
    },
    "globalCompanyNameType": {
      "type": "string",
      "pattern": "^[ -~¡-ÿĀ-ʯḀ-ỿ‐-―‘-‟₠-₿ÅK]{1,160}$"
    },
    "utrType": {
      "type": "string",
      "pattern": "^[0-9]{10}$"
    },
    "legalEntityIdentifierType": {
      "type": "string",
      "pattern": "^[0-9A-Z]{18}[0-9]{2}$"
    },
    "dateType": {
      "type": "string",
      "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
    },
    "countryCodesType": {
      "type": "string",
      "enum": ["AD", "AE", "AF", "AG", "AI", "AL", "AM", "AN", "AO", "AQ", "AR", "AS", "AT", "AU", "AW", "AX", "AZ", "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BM", "BN", "BO", "BQ", "BR", "BS", "BT", "BV", "BW", "BY", "BZ", "CA", "CC", "CD", "CF", "CG", "CH", "CI", "CK", "CL", "CM", "CN", "CO", "CR", "CS", "CU", "CV", "CW", "CX", "CY", "CZ", "DD", "DE", "DJ", "DK", "DM", "DO", "DZ", "EC", "EE", "EG", "EH", "ER", "ES", "ET", "EU", "FI", "FJ", "FK", "FM", "FO", "FR", "GA", "GD", "GE", "GF", "GG", "GH", "GI", "GL", "GM", "GN", "GP", "GQ", "GR", "GS", "GT", "GU", "GW", "GY", "HK", "HM", "HN", "HR", "HT", "HU", "ID", "IE", "IL", "IM", "IN", "IO", "IQ", "IR", "IS", "IT", "JE", "JM", "JO", "JP", "KE", "KG", "KH", "KI", "KM", "KN", "KP", "KR", "KW", "KY", "KZ", "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV", "LY", "MA", "MC", "MD", "ME", "MF", "MG", "MH", "MK", "ML", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "MY", "MZ", "NA", "NC", "NE", "NF", "NG", "NI", "NL", "NO", "NP", "NR", "NT", "NU", "NZ", "OM", "PA", "PE", "PF", "PG", "PH", "PK", "PL", "PM", "PN", "PR", "PS", "PT", "PW", "PY", "QA", "RE", "RO", "RS", "RU", "RW", "SA", "SB", "SC", "SD", "SE", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SR", "SS", "ST", "SV", "SX", "SY", "SZ", "TC", "TD", "TF", "TG", "TH", "TJ", "TK", "TL", "TM", "TN", "TO", "TP", "TR", "TT", "TV", "TW", "TZ", "UA", "UG", "UK", "UM", "UN", "US", "UY", "UZ", "VA", "VC", "VE", "VG", "VI", "VN", "VU", "WF", "WS", "YE", "YT", "ZA", "ZM", "ZW"]
    }
  }
}

=== hmrc/interest-restriction-return-dynamic-stub/conf/resources/examples/example_revoke_irr_reporting_company_body.json
{
  "agentDetails": {
    "agentActingOnBehalfOfCompany": true,
    "agentName": "AAgent"
  },
  "reportingCompany": {
    "companyName": "ACompany",
    "ctutr": "1123456789",
    "sameAsUltimateParent": true
  },
  "isReportingCompanyRevokingItself": false,
  "companyMakingRevocation": {
    "companyName": "BCompany",
    "countryOfIncorporation": "UK",
    "ctutr": "9999999999",
    "legalEntityIdentifier": "Z29900T8BM49AURSDO53"
  },
  "authorisingCompanies": [
    {
      "companyName": "CCompany",
      "utr": "5555555555",
      "consenting": true
    },
    {
      "companyName": "D-Company, with unusual chars & % ! | ~ #",
      "utr": "1122334455",
      "consenting": true
    }
  ],
  "ultimateParentCompany": {
    "isUk": true,
    "companyName": "E*Company$$",
    "ctutr": "0000000000",
    "sautr": "1237658890",
    "knownAs": "Mabel",
    "countryOfIncorporation": "ZA",
    "legalEntityIdentifier": "549300QKDHYRRQH2MB86"
  },
  "accountingPeriod": {
    "startDate": "2018-11-01",
    "endDate": "2019-12-01"
  },
  "declaration": true
}
