=== hmrc/interest-restriction-return-dynamic-stub/conf/resources/irr/schemas/abbreviated.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"additionalProperties": false,
	"properties": {
	    "declaration": {
      		"type": "boolean"
    	},
		"agentDetails": {
			"description": "Required.",
			"type": "object",
			"additionalProperties": false,
			"required": [
				"agentActingOnBehalfOfCompany"
			],
			"properties": {
				"agentActingOnBehalfOfCompany": {
					"description": "Required.",
					"type": "boolean"
				},
				"agentName": {
					"$ref": "#/definitions/ukCompanyNameType"
				}
			}
		},
		"reportingCompany": {
			"description": "Required. The details of the reporting company",
			"type": "object",
			"additionalProperties": false,
			"required": [
				"companyName",
				"ctutr",
				"sameAsUltimateParent"
			],
			"properties": {
				"companyName": {
					"$ref": "#/definitions/ukCompanyNameType"
				},
				"ctutr": {
					"$ref": "#/definitions/utrType"
				},
				"sameAsUltimateParent": {
					"description": "Required.",
					"type": "boolean"
				}
			}
		},
		"parentCompany": {
			"description": "Optional.Details of the parent company, this can be either an ultimate parent company or a deemed parent",
			"oneOf": [{
					"additionalProperties": false,
					"properties": {
						"ultimateParent": {
							"$ref": "#/definitions/parentType"
						}
					},
					"required": [
						"ultimateParent"
					]
				},
				{
					"additionalProperties": false,
					"properties": {
						"deemedParent": {
							"type": "array",
							"minItems": 2,
							"maxItems": 3,
							"items": {
								"$ref": "#/definitions/parentType"
							}
						}
					},
					"required": [
						"deemedParent"
					]
				}
			],
			"type": "object"
		},
		"publicInfrastructure": {
			"description": "Required.",
			"type": "boolean"
		},
		"groupCompanyDetails": {
			"description": "Required. Details of the group company.",
			"type": "object",
			"additionalProperties": false,
			"required": [
				"totalCompanies",
				"accountingPeriod"
			],
			"properties": {
				"totalCompanies": {
					"description": "Required.",
					"type": "integer",
					"minimum": 1
				},
				"accountingPeriod": {
					"description": "Required.",
					"type": "object",
					"additionalProperties": false,
					"required": [
						"startDate",
						"endDate"
					],
					"properties": {
						"startDate": {
							"$ref": "#/definitions/dateType"
						},
						"endDate": {
							"$ref": "#/definitions/dateType"
						}
					}
				}
			}
		},
		"submissionType": {
			"description": "Required.",
			"type": "string",
			"enum": [
				"original",
				"revised"
			]
		},
		"revisedReturnDetails": {
			"$ref": "#/definitions/explanatoryNotesShort"
		},
		"angie": {
			"description": "Optional.",
			"type": "number",
			"minimum": 0,
			"multipleOf": 0.01
		},
		"ukCompanies": {
			"description": "Required.",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"companyName": {
						"$ref": "#/definitions/ukCompanyNameType"
					},
					"utr": {
						"$ref": "#/definitions/utrType"
					},
					"consenting": {
						"description": "Required.",
						"type": "boolean"
					},
					"qicElection": {
						"description": "Required.",
						"type": "boolean"
					}
				},
				"required": [
					"companyName",
					"utr",
					"consenting",
					"qicElection"
				]
			}
		},
		"groupLevelElections": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"groupRatio": {
					"description": "Required.",
					"type": "object",
					"additionalProperties": false,
					"required": [
						"isElected",
						"activeGroupEBITDAChargeableGains"
					],
					"properties": {
						"isElected": {
							"description": "Required.",
							"type": "boolean"
						},
						"groupRatioBlended": {
							"description": "Optional.",
							"type": "object",
							"additionalProperties": false,
							"properties": {
								"isElected": {
									"description": "Required.",
									"type": "boolean"
								},
								"investorGroups": {
									"description": "Optional. An array of group company names.",
									"type": "array",
									"minItems": 1,
									"items": {
										"type": "object",
										"additionalProperties": false,
										"properties": {
											"groupName": {
												"$ref": "#/definitions/globalCompanyNameType"
											},
											"elections": {
												"description": "The elections made by this investor group",
												"type": "array",
												"maxItems": 5,
												"items": {
													"type": "string",
													"enum": [
														"groupRatioBlended",
														"groupEBITDA",
														"interestAllowanceAlternativeCalculation",
														"interestAllowanceNonConsolidatedInvestment",
														"interestAllowanceConsolidatedPartnership"
													]
												}
											}
										},
										"required": [
											"groupName"
										]
									}
								}
							},
							"required": [
								"isElected"
							]
						},
						"groupEBITDAChargeableGains": {
							"description": "Optional.",
							"type": "boolean"
						},
						"activeGroupEBITDAChargeableGains": {
							"type": "boolean"
						}
					}
				},
				"interestAllowanceAlternativeCalculation": {
					"description": "Required.",
					"type": "boolean"
				},
				"activeInterestAllowanceAlternativeCalculation": {
					"description": "Required.",
					"type": "boolean"
				},
				"interestAllowanceNonConsolidatedInvestment": {
					"description": "Required.",
					"type": "object",
					"additionalProperties": false,
					"required": [
						"isElected"
					],
					"properties": {
						"isElected": {
							"description": "Required.",
							"type": "boolean"
						},
						"nonConsolidatedInvestments": {
							"description": "Optional.",
							"type": "array",
							"minItems": 1,
							"items": {
								"type": "object",
								"additionalProperties": false,
								"properties": {
									"investmentName": {
										"$ref": "#/definitions/explanatoryNotesShort"
									}
								},
								"required": [
									"investmentName"
								]
							}
						}
					}
				},
				"interestAllowanceConsolidatedPartnership": {
					"description": "Required.",
					"type": "object",
					"additionalProperties": false,
					"required": [
						"isElected",
						"isActive"
					],
					"properties": {
						"isElected": {
							"type": "boolean"
						},
						"isActive": {
							"type": "boolean"
						},
						"consolidatedPartnerships": {
							"description": "Optional.",
							"type": "array",
							"minItems": 1,
							"items": {
								"type": "object",
								"additionalProperties": false,
								"properties": {
									"partnershipName": {
										"$ref": "#/definitions/globalCompanyNameType"
									},
									"sautr": {
										"$ref": "#/definitions/utrType"
									}
								},
								"required": [
									"partnershipName"
								]
							}
						}
					}
				}
			},
			"required": [
				"groupRatio",
				"interestAllowanceAlternativeCalculation",
				"activeInterestAllowanceAlternativeCalculation",
				"interestAllowanceNonConsolidatedInvestment",
				"interestAllowanceConsolidatedPartnership"
			]
		},
	    "numberOfUkCompanies": {
	      "description": "Number of UK Companies",
	      "type": "integer",
	      "minimum": 1
	    }
	},
	"required": [
		"declaration",
		"agentDetails",
		"reportingCompany",
		"publicInfrastructure",
		"groupCompanyDetails",
		"submissionType",
		"ukCompanies"
	],
	"definitions": {
		"ukCompanyNameType": {
			"description": "Allow Unicode blocks Basic Latin (Space to Tilde), printable Latin-1 Supplement (¡ to ÿ), and all of Latin Extended-A and Latin Extended-B and IP Extensions (Ā to ʯ), all the Latin Extended Additional characters (Ḁ to ỿ), General Punctuation characters Hyphen to Horizontal Bar (‐ to ―), General Punctuation characters (‘ to ‟), Currency Symbol characters (₠ to ₿), Letterlike Symbols Å and K",
			"type": "string",
			"pattern": "^[ -~¡-ÿĀ-ʯḀ-ỿ‐-―‘-‟₠-₿ÅK]{1,160}$"
		},
		"globalCompanyNameType": {
			"type": "string",
			"description": "Allow Unicode blocks Basic Latin (Space to Tilde), printable Latin-1 Supplement (¡ to ÿ), and all of Latin Extended-A and Latin Extended-B and IP Extensions (Ā to ʯ), all the Latin Extended Additional characters (Ḁ to ỿ), General Punctuation characters Hyphen to Horizontal Bar (‐ to ―), General Punctuation characters (‘ to ‟), Currency Symbol characters (₠ to ₿), Letterlike Symbols Å and K",
			"pattern": "^[ -~¡-ÿĀ-ʯḀ-ỿ‐-―‘-‟₠-₿ÅK]{1,160}$"
		},
		"utrType": {
			"description": "A UTR of 10 numeric characters",
			"type": "string",
			"pattern": "^[0-9]{10}$"
		},
		"legalEntityIdentifierType": {
			"type": "string",
			"description": "A Legal Entity Identifier (LEI); format is as per the ISO 17442 standard - 18 uppercase alphabetic or numeric characters followed by 2 numeric characters",
			"pattern": "^[0-9A-Z]{18}[0-9]{2}$"
		},
		"explanatoryNotesShort": {
			"description": "",
			"type": "string",
			"pattern": "^[ -~¢-¥©®±×÷‐₠-₿−-∝≈≠≣-≥]{1,5000}$",
			"title": ""
		},
		"dateType": {
			"description": "Format YYYY-MM-DD in the range 1900-01-01 to 2099-12-31 accommodating leap years",
			"type": "string",
			"pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
		},
		"parentType": {
			"description": "Required. The details of the ultimate parent company",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"isUk": {
					"description": "Required.",
					"type": "boolean"
				},
				"companyName": {
					"$ref": "#/definitions/globalCompanyNameType"
				},
				"ctutr": {
					"$ref": "#/definitions/utrType"
				},
				"sautr": {
					"$ref": "#/definitions/utrType"
				},
				"knownAs": {
					"$ref": "#/definitions/globalCompanyNameType"
				},
				"countryOfIncorporation": {
					"$ref": "#/definitions/countryCodesType"
				},
				"legalEntityIdentifier": {
					"$ref": "#/definitions/legalEntityIdentifierType"
				}
			},
			"required": [
				"isUk",
				"companyName"
			]
		},
		"countryCodesType": {
			"description": "List of ISO 3166-1 2 Alpha Country Codes",
			"type": "string",
			"enum": [
				"AD",
				"AE",
				"AF",
				"AG",
				"AI",
				"AL",
				"AM",
				"AN",
				"AO",
				"AQ",
				"AR",
				"AS",
				"AT",
				"AU",
				"AW",
				"AX",
				"AZ",
				"BA",
				"BB",
				"BD",
				"BE",
				"BF",
				"BG",
				"BH",
				"BI",
				"BJ",
				"BM",
				"BN",
				"BO",
				"BQ",
				"BR",
				"BS",
				"BT",
				"BV",
				"BW",
				"BY",
				"BZ",
				"CA",
				"CC",
				"CD",
				"CF",
				"CG",
				"CH",
				"CI",
				"CK",
				"CL",
				"CM",
				"CN",
				"CO",
				"CR",
				"CS",
				"CU",
				"CV",
				"CW",
				"CX",
				"CY",
				"CZ",
				"DD",
				"DE",
				"DJ",
				"DK",
				"DM",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"EH",
				"ER",
				"ES",
				"ET",
				"EU",
				"FI",
				"FJ",
				"FK",
				"FM",
				"FO",
				"FR",
				"GA",
				"GD",
				"GE",
				"GF",
				"GG",
				"GH",
				"GI",
				"GL",
				"GM",
				"GN",
				"GP",
				"GQ",
				"GR",
				"GS",
				"GT",
				"GU",
				"GW",
				"GY",
				"HK",
				"HM",
				"HN",
				"HR",
				"HT",
				"HU",
				"ID",
				"IE",
				"IL",
				"IM",
				"IN",
				"IO",
				"IQ",
				"IR",
				"IS",
				"IT",
				"JE",
				"JM",
				"JO",
				"JP",
				"KE",
				"KG",
				"KH",
				"KI",
				"KM",
				"KN",
				"KP",
				"KR",
				"KW",
				"KY",
				"KZ",
				"LA",
				"LB",
				"LC",
				"LI",
				"LK",
				"LR",
				"LS",
				"LT",
				"LU",
				"LV",
				"LY",
				"MA",
				"MC",
				"MD",
				"ME",
				"MF",
				"MG",
				"MH",
				"MK",
				"ML",
				"MM",
				"MN",
				"MO",
				"MP",
				"MQ",
				"MR",
				"MS",
				"MT",
				"MU",
				"MV",
				"MW",
				"MX",
				"MY",
				"MZ",
				"NA",
				"NC",
				"NE",
				"NF",
				"NG",
				"NI",
				"NL",
				"NO",
				"NP",
				"NR",
				"NT",
				"NU",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PF",
				"PG",
				"PH",
				"PK",
				"PL",
				"PM",
				"PN",
				"PR",
				"PS",
				"PT",
				"PW",
				"PY",
				"QA",
				"RE",
				"RO",
				"RS",
				"RU",
				"RW",
				"SA",
				"SB",
				"SC",
				"SD",
				"SE",
				"SG",
				"SH",
				"SI",
				"SJ",
				"SK",
				"SL",
				"SM",
				"SN",
				"SO",
				"SR",
				"SS",
				"ST",
				"SV",
				"SX",
				"SY",
				"SZ",
				"TC",
				"TD",
				"TF",
				"TG",
				"TH",
				"TJ",
				"TK",
				"TL",
				"TM",
				"TN",
				"TO",
				"TP",
				"TR",
				"TT",
				"TV",
				"TW",
				"TZ",
				"UA",
				"UG",
				"UK",
				"UM",
				"UN",
				"US",
				"UY",
				"UZ",
				"VA",
				"VC",
				"VE",
				"VG",
				"VI",
				"VN",
				"VU",
				"WF",
				"WS",
				"YE",
				"YT",
				"ZA",
				"ZM",
				"ZW"
			]
		},
		"errorResponse": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"failures"
			],
			"properties": {
				"failures": {
					"type": "array",
					"minItems": 1,
					"uniqueItems": true,
					"items": {
						"type": "object",
						"additionalProperties": false,
						"required": [
							"code",
							"reason"
						],
						"properties": {
							"code": {
								"description": "Keys for all the errors returned",
								"type": "string",
								"pattern": "^[A-Z0-9_-]{1,160}$"
							},
							"reason": {
								"description": "A simple description for the failure",
								"type": "string",
								"minLength": 1,
								"maxLength": 160
							}
						}
					}
				}
			}
		},
		"response": {
			"type": "object",
			"properties": {
				"acknowledgementReference": {
					"type": "string",
					"description": "A reference for the stored record",
					"minLength": 4,
					"maxLength": 36
				}
			},
			"required": [
				"acknowledgementReference"
			]
		}
	}
}

=== hmrc/interest-restriction-return-dynamic-stub/conf/resources/examples/example_abbreviated_irr_reporting_company_body.json
{
  "declaration": true,
  "agentDetails": {
    "agentActingOnBehalfOfCompany": true,
    "agentName": "Some agent"
  },
  "reportingCompany": {
    "companyName": "A Reporting Company",
    "ctutr": "1123456747",
    "sameAsUltimateParent": true
  },
  "parentCompany": {
    "ultimateParent": {
      "isUk": true,
      "ctutr": "8764783632",
      "sautr": "0897876656",
      "knownAs": "$$=!|~Ḁỿ",
      "legalEntityIdentifier": "213800WRYCD72WGOOY58",
      "companyName": "$$=!|~Ḁỿ",
      "countryOfIncorporation": "JP"
    }
  },
  "publicInfrastructure": true,
  "groupCompanyDetails": {
    "totalCompanies": 1,
    "accountingPeriod": {
      "startDate": "1920-02-29",
      "endDate": "1920-02-29"
    }
  },
  "submissionType": "original",
  "revisedReturnDetails": "Calculation symbols and formulae y=x,  73463784 ÷ (839393987 + 73678979)",
  "angie": 0.01,
  "groupLevelElections": {
    "activeInterestAllowanceAlternativeCalculation": true,
    "groupRatio": {
      "activeGroupEBITDAChargeableGains": true,
      "isElected": true,
      "groupRatioBlended": {
        "isElected": true,
        "investorGroups": [
          {
            "groupName": "₠ ₡ ₢ ₣ ₤ ₥ ₦ ₧ ₨ ₩ ₪ ₫ € ₭ ₮ ₯ ₰ ₱ ₲",
            "elections": [
              "groupRatioBlended",
              "groupEBITDA",
              "interestAllowanceAlternativeCalculation",
              "interestAllowanceNonConsolidatedInvestment",
              "interestAllowanceConsolidatedPartnership"
            ]
          },
          {
            "groupName": " ₰ ₱ ₲ ₳ ₴ ₵ ₶ ₷ ₸ ₹ ₺ ₻ ₼ ₽ ₾ ₿"
          }
        ]
      },
      "groupEBITDAChargeableGains": true
    },
    "interestAllowanceAlternativeCalculation": true,
    "interestAllowanceNonConsolidatedInvestment": {
      "isElected": true,
      "nonConsolidatedInvestments": [
        {
          "investmentName": "Investment 12323"
        },
        {
          "investmentName": "Investment C"
        }
      ]
    },
    "interestAllowanceConsolidatedPartnership": {
      "isElected": true,
      "isActive": true,
      "consolidatedPartnerships": [
        {
          "partnershipName": "Öbs",
          "sautr": "3466564633"
        },
        {
          "partnershipName": "Äßß",
          "sautr": "9495644574"
        }
      ]
    }
  },
  "ukCompanies": [
    {
      "companyName": "!!Company A$$$==",
      "utr": "7634834546",
      "consenting": true,
      "qicElection": true
    },
    {
      "companyName": "!!Company B $$$==",
      "utr": "7236453286",
      "consenting": true,
      "qicElection": true
    }
  ]
}
